export const enum AnnounceType {
  UpdateChatMessages,
  RoomName,
  RemoteInsert,
  RemoteRemove,
  RemoteAllMessages,
  ChangeLanguage,
  ReadyToDisplayMonaco,
  CursorChange,
  SelectionChange,
  PeerLeft,
  NewPeerJoining,
  LeftHomePage,
  CrdtPackageReady,
  ChangePeerName,
  ChangeMyName,
  UnhandledError,
}
