export const enum AnnounceType {
  UpdateChatMessages = 0,
  RoomName = 1,
  RemoteInsert = 2,
  RemoteRemove = 3,
  RemoteAllMessages = 4,
  ChangeLanguage = 5,
  ReadyToDisplayMonaco = 6,
  CursorChange = 7,
  SelectionChange = 8,
  PeerLeft = 9,
  NewPeerJoining = 10,
  LeftHomePage = 11,
  CrdtPackageReady = 12,
  ChangePeerName = 13,
  ChangeMyName = 14,
  UnhandledError = 15,
}
