export const Languages = [
  { name: 'ABAP', value: 'abap' },
  { name: 'AES', value: 'aes' },
  { name: 'Apex', value: 'apex' },
  { name: 'Azure CLI', value: 'azcli' },
  { name: 'Bat', value: 'bat' },
  { name: 'C', value: 'c' },
  { name: 'Clojure', value: 'clojure' },
  { name: 'CoffeeScript', value: 'coffeescript' },
  { name: 'C++', value: 'cpp' },
  { name: 'C#', value: 'csharp' },
  { name: 'CSP', value: 'csp' },
  { name: 'CSS', value: 'css' },
  { name: 'Docker', value: 'dockerfile' },
  { name: 'F#', value: 'fsharp' },
  { name: 'Go', value: 'go' },
  { name: 'GraphQL', value: 'graphql' },
  { name: 'Handlebars', value: 'handlebars' },
  { name: 'HTML', value: 'html' },
  { name: 'ini', value: 'ini' },
  { name: 'Java', value: 'java' },
  { name: 'JavaScript', value: 'javascript' },
  { name: 'JSON', value: 'json' },
  { name: 'Kotlin', value: 'kotlin' },
  { name: 'LESS', value: 'less' },
  { name: 'Lua', value: 'lua' },
  { name: 'Markdown', value: 'markdown' },
  { name: 'MIPS', value: 'mips' },
  { name: 'Microsoft DAX', value: 'msdax' },
  { name: 'MySQL', value: 'mysql' },
  { name: 'Objective-C', value: 'objective-c' },
  { name: 'Pascal', value: 'pascal' },
  { name: 'Perl', value: 'perl' },
  { name: 'PostgreSQL', value: 'pgsql' },
  { name: 'PHP', value: 'php' },
  { name: 'Plain Text', value: 'plaintext' },
  { name: 'Power Query', value: 'powerquery' },
  { name: 'Power Shell', value: 'powershell' },
  { name: 'Pug', value: 'pug' },
  { name: 'Python', value: 'python' },
  { name: 'R', value: 'r' },
  { name: 'Razor', value: 'razor' },
  { name: 'Redis', value: 'redis' },
  { name: 'Redshift', value: 'redshift' },
  { name: 'reStructuredText', value: 'restructuredtext' },
  { name: 'Ruby', value: 'ruby' },
  { name: 'Rust', value: 'rust' },
  { name: 'Small Basic', value: 'sb' },
  { name: 'Scheme', value: 'scheme' },
  { name: 'SCSS', value: 'scss' },
  { name: 'Shell', value: 'shell' },
  { name: 'SOL', value: 'sol' },
  { name: 'SQL', value: 'sql' },
  { name: 'Structured Text', value: 'st' },
  { name: 'Swift', value: 'swift' },
  { name: 'Tcl', value: 'tcl' },
  { name: 'Twig', value: 'twig' },
  { name: 'Typescript', value: 'typescript' },
  { name: 'Visual Basic', value: 'vb' },
  { name: 'XML', value: 'xml' },
  { name: 'YAML', value: 'yaml' },
];
