// <auto-generated />
using CodeSpotP2P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeSpot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200704230552_First Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("CodeSpotP2P.Model.Peer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PeerId");

                    b.Property<string>("RoomName");

                    b.HasKey("Id");

                    b.HasIndex("RoomName");

                    b.ToTable("peers");
                });

            modelBuilder.Entity("CodeSpotP2P.Model.Room", b =>
                {
                    b.Property<string>("RoomName")
                        .ValueGeneratedOnAdd();

                    b.HasKey("RoomName");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("CodeSpotP2P.Model.Peer", b =>
                {
                    b.HasOne("CodeSpotP2P.Model.Room", "Room")
                        .WithMany("peers")
                        .HasForeignKey("RoomName");
                });
#pragma warning restore 612, 618
        }
    }
}
