// <auto-generated />
using CodeSpotP2P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeSpotP2P.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200607173509_ChangePKOfCRDTTable")]
    partial class ChangePKOfCRDTTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("Code_Spot.Models.CRDT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CRDTObject");

                    b.Property<string>("RoomName");

                    b.HasKey("Id");

                    b.HasIndex("RoomName")
                        .IsUnique();

                    b.ToTable("CRDTs");
                });

            modelBuilder.Entity("Code_Spot.Models.Room", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Code_Spot.Models.CRDT", b =>
                {
                    b.HasOne("Code_Spot.Models.Room", "Room")
                        .WithOne("Crdt")
                        .HasForeignKey("Code_Spot.Models.CRDT", "RoomName");
                });
#pragma warning restore 612, 618
        }
    }
}
