// <auto-generated />
using CodeSpot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeSpot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200529182457_RoomAndCRDTMigrations")]
    partial class RoomAndCRDTMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("Code_Spot.Models.CRDT", b =>
                {
                    b.Property<string>("CRDTObject");

                    b.Property<string>("RoomName");

                    b.HasKey("CRDTObject", "RoomName");

                    b.HasIndex("RoomName")
                        .IsUnique();

                    b.ToTable("CRDTs");
                });

            modelBuilder.Entity("Code_Spot.Models.Room", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Code_Spot.Models.CRDT", b =>
                {
                    b.HasOne("Code_Spot.Models.Room", "Room")
                        .WithOne("Crdt")
                        .HasForeignKey("Code_Spot.Models.CRDT", "RoomName")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
