export const Languages = [
    { name: 'Bat', value: 'bat' },
    { name: 'C', value: 'c' },
    { name: 'C++', value: 'cpp' },
    { name: 'C#', value: 'csharp' },
    { name: 'Go', value: 'go' },
    { name: 'HTML', value: 'html' },
    { name: 'Java', value: 'java' },
    { name: 'Kotlin', value: 'kotlin' },
    { name: 'MySQL', value: 'mysql' },
    { name: 'JavaScript', value: 'javascript' },
    { name: 'PgSQL', value: 'pgsql' },
    { name: 'Plain Text', value: 'plaintext' },
    { name: 'Python', value: 'python' },
    { name: 'Ruby', value: 'ruby' },
    { name: 'Scheme', value: 'scheme' },
    { name: 'Shell', value: 'shell' },
    { name: 'SQL', value: 'sql' },
    { name: 'Swift', value: 'swift' },
    { name: 'Typescript', value: 'typescript' },
  ];

